config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :categories do
    resources :payments
  end
  devise_for :users
  devise_scope :user do
    get '/logout', to: 'devise/sessions#destroy'
  end
  root to: 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :payments, dependent: :destroy

  validates :name, presence: true, length: { maximum: 60 }
  validates :icon, presence: true

  def total_transaction_amount
    payments.sum(:amount)
  end
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
  has_many :category, dependent: :destroy

  validates :name, presence: true, length: { maximum: 30 }
  validates :amount, presence: true, numericality: { greater_than: 0, only_integer: true }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :categories, dependent: :destroy
  has_many :payments, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# The ApplicationHelper module contains helper methods that can be used across views
# and other parts of the Rails application. These methods are accessible to all views
# and provide reusable functionality to assist with rendering and other tasks.

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]
  before_action :authenticate_user!

  def index
    @categories = Category.includes(:payments).where(user_id: current_user.id).order(updated_at: :desc)
  end

  def show
    redirect_to new_category_payment_path(@category)
  end

  def new
    @category = current_user.categories.new
  end

  def edit; end

  def create
    @category = Category.new(category_params)
    @category.user = current_user
    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: 'Category was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: %i[show edit update destroy]

  def index
    @category = Category.find(params[:category_id])
    @payments = Payment.where(user: current_user, category_id: @category.id).order(updated_at: :desc)
    @total = Payment.where(user: current_user, category_id: @category.id).sum(:amount)
  end

  def show
    @category = Category.find(params[:category_id])
    @payment = Payment.find(params[:id])
  end

  def new
    @category = Category.find(params[:category_id])
    @payment = Payment.new
  end

  def edit; end

  def create
    @payment = Payment.new(payment_params)
    @payment.user_id = current_user.id
    category = Category.find(params[:category_id])
    @payment.category_id = category.id

    respond_to do |format|
      if @payment.save
        format.html do
          redirect_to category_payments_url(category_id: @payment.category_id),
                      notice: 'Payment was successfully created.'
        end
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to payment_url(@payment), notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @payment.destroy
    redirect_to payments_url, notice: 'Payment was successfully destroyed.'
  end

  private

  def set_payment
    @payment = Payment.find(params[:id])
  end

  def payment_params
    params.require(:payment).permit(:name, :amount)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    redirect_to categories_path if user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/categories/index.html.erb
<%# <div class="category_head">
<h2>My Categories</h2>
<a href="/logout">
<i style='font-size:24px' class='fas'>&#xf2f5;</i>
</a>
</div> %>
 <nav class="navbar navbar-expand-md navbar-light bg-3778c2 ">
     <button class="navbar-toggler" data-toggle="collapse" data-target="#collapsibleNavbar">
            <i class="fa-solid fa-bars" id="mobile-menu"></i>
        </button>
          <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                <a class="nav-link" href="/logout">Logout</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Item 2</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Item 3</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Item 4</a>
                </li>
            </ul>
        </div>
        <!-- Brand/logo -->
        <a class="navbar-brand text-white" href="#">CARTEGORIES</a>
        
        <!-- Mobile Menu with Navbar Text and Magnifying Glass Icon -->
        <div class="d-md-none d-flex align-items-center mr-auto m-2">
            <i class="fas fa-search" id="search-icon"></i>
        </div>

        <!-- Toggler/collapsible Button -->
        
        
        <!-- Navbar links -->
     
    </nav>

 <div>
    <% if @categories.nil? %>
      <h3>Add a Category</h3>
    <% else %>
    <% @categories.each do |category| %>
   <a href="<%= category_payments_path(category.id) %>">
    <div class = "category">
    <img src= "<%= category.icon %>" alt="icon" calss="icon">
    <p><%= category.name %></p>
    <p> Total: <%= category.total_transaction_amount%>$</p>
    </div>
    <% end %>
    <% end %>
     <div class = "footer_container">
     <a href="/categories/new">
        <div class = "footer">
            <p>Add Category</p>
            <i class="fa-solid fa-plus"></i>
        </div>
     </a>
    </div>
  </div>

app/views/categories/new.html.erb
<div class = "category_head">
     <a href="<%= categories_path %>">
            <i class="fa-solid fa-arrow-left" id = "left-arrow"></i>
        </a>
    <h2>New Category</h2>
    <a href="/logout" id = "left-arrow">
        LOG OUT
    </a>
</div>
<%= form_with(model: @category, url:categories_path) do |form| %>
    <div class= "form-container">
        <%= form.text_field :name, placeholder: "Name" %>
        <%= form.text_field :icon, placeholder: "brand logo" %>
        <%= form.submit "Create", class: "submit-button" %>
    </div>
<% end %>

app/views/categories/show.html.erb
<%= link_to "Back", categories_path%>
<% render @category%>
<div>
 <%= link_to, edit_category_path(@category)%>
 <% link_to "Destroy", @category, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>smartbudget</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
   <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/payments/index.html.erb
<div class = "category_head">
<a href= "<%= categories_path %>">
<i class="fa-solid fa-arrow-left" id = "left-arrow"></i></a>
<h2> transaction</h2>
<a href = "/logout" id = "nav-txt">
Log out
</a>
</div>

<div>
<% if @payments.nil? %>
 <p>No transaction available for now.</p>
 <% else %>
 <% @payments.each do |payment| %>
<p> Total: <%= @category.total_transaction_amount%>$</p>
 <div class = "category" >
   <p><%= payment.name %></p>
   <p>Price: <%= payment.amount %>$ </p>
 </div>
 <% end %>
 <% end %>
 <div class = "footer_container">
 <div class ="footer">
 <%= link_to 'Add New Transaction', new_category_payment_path, class: "footer_link" %>
 <i class="fa-solid fa-plus"></i>
 </div>
 </div>
</div>

app/views/payments/new.html.erb
<%= form_with(model: @payment, url: category_payments_path) do |form| %>
<div class = "category_head">
   <a href ="<%= category_payments_path %>"><i class="fa-solid fa-arrow-left" id="left-arrow"></i></a>
   <p> New Transaction </p>
    <a href="/logout" id = "left-arrow" >
        Log out
    </a>
</div>

<div class = "form-container">
 <%= form.text_field :name, placeholder: " Name "%>
 <%= form.text_field :amount, placeholder: " Price "%>
 <%= form.submit "create", class: "submit-button" %>
</div>
<% end %>

app/views/payments/show.html.erb
<%= render @payment %>

<div>
  <%= link_to "Edit", edit_payment_path(@payment) %> |
  <%= link_to "Back", payments_path %>

  <%= button_to "Destroy", @payment, method: :delete %>
</div>

app/views/users/index.html.erb
<div class="container">
<h1 class="title">Smartbudget</h1>
<div class="buttons">
    <%= link_to "Log In" , new_user_session_path, class: "signin" %>
    <%= link_to "Sign Up" , new_user_registration_path, class: "signup" %>
</div>
</div>